# Generated by Django 5.1.7 on 2025-03-26 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='calca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cor', models.CharField(max_length=100)),
                ('tamanho', models.CharField(max_length=100)),
                ('preco', models.CharField(max_length=100)),
                ('imagem', models.ImageField(blank=True, upload_to='fotos/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='camisa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cor', models.CharField(max_length=100)),
                ('tamanho', models.CharField(max_length=100)),
                ('preco', models.CharField(max_length=100)),
                ('imagem', models.ImageField(blank=True, upload_to='fotos/%Y/%m/%d/')),
            ],
        ),
    ]
